// <auto-generated />
using System;
using Dbst.Transaction.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dbst.Transaction.Infra.Data.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20200415034851_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Dbst.Transaction.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Agency");

                    b.Property<double>("Balance");

                    b.Property<string>("Digit");

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agency = "1234",
                            Balance = 1000.0,
                            Digit = "0",
                            Number = "012345"
                        },
                        new
                        {
                            Id = 2,
                            Agency = "4567",
                            Balance = 2500.0,
                            Digit = "1",
                            Number = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Agency = "7890",
                            Balance = 350.5,
                            Digit = "2",
                            Number = "150000"
                        });
                });

            modelBuilder.Entity("Dbst.Transaction.Domain.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("FromAccountId");

                    b.Property<int>("ToAccountId");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            Created = new DateTime(2020, 4, 15, 3, 48, 51, 634, DateTimeKind.Utc).AddTicks(5392),
                            FromAccountId = 1,
                            ToAccountId = 2,
                            Value = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
